services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    image: iot-firmware-update-backend:local
    ports:
      - "3000:3000"
    depends_on:
      - localstack 
    environment:
      - NODE_ENV=development
      - AWS_ENDPOINT_URL=http://localstack:4566
      - AWS_REGION=us-east-1
      - AWS_ACCESS_KEY_ID=test
      - AWS_SECRET_ACCESS_KEY=test
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000/health || exit 1"]
      interval: 5s
      timeout: 3s
      retries: 8

  simulator:
    build:
      context: ./simulator
      dockerfile: Dockerfile
    image: iot-firmware-update-simulator:local
    depends_on:
      - backend
    environment:
      - BACKEND_URL=http://backend:3000

  localstack:
    image: localstack/localstack:latest
    environment:
      - AWS_DEFAULT_REGION=us-east-1
      - AWS_ACCESS_KEY_ID=test
      - AWS_SECRET_ACCESS_KEY=test
      - SERVICES=s3
    ports:
      - "4566:4566"
    volumes:
      - localstack-data:/tmp/localstack

volumes:
  localstack-data: